### ISSUE TITLE
Throws in library functions not propagated to caller

### ISSUE THREAD

**Issue by olekon** [maraoz/lib#4]
If you add in the Example library `setUint` function a require statement and try to call it with 'bad' parameters, you'll notice that MyContract's `set` function doesn't throw. For example

 ```
 function setUint(LibInterface.S storage s, uint i) {
    require(i>10);
    s.i = i;
  }
```

later in test.js (I will use async/await syntax)

```
it("should fail", async function() {
         try {
             await thecontract.set(1);
         } catch (e) {
             return true;
         }
         assert.isTrue(false, "Function should fail");        
 })
```

'truffle test' fails the assertion because function `set` doesn't throw. Although state haven't changed either. But if `MyContract.set` is a payable function the payment is not cancelled.

Is the reason of this behaviour somewhere in Dispatcher's `assembly {}` code? I suppose it should also throw if delegated function throws an exception.

**Comment by maraoz** [comment]
Very interesting. That should be the behavior, clearly. If you find a solution let me know, I won't have time to look into this in detail for some time.

**Comment by olekon** [comment]
I found the solution. We should check the `delegatecall` result.

According to http://solidity.readthedocs.io/en/develop/control-structures.html

> When exceptions happen in a sub-call, they “bubble up” (i.e. exceptions are rethrown) automatically. Exceptions to this rule are send and the low-level functions call, delegatecall and callcode – those return false in case of an exception instead of “bubbling up”.

Fixed version of Dispatcher's fallback function. I also added `payable` modifier to be able to delegate payable functions to dispatcher. 

```
    function() payable {
        LibDispatcherStorage dispatcherStorage = LibDispatcherStorage(...);
        uint32 len = dispatcherStorage.sizes(msg.sig);
        address target = dispatcherStorage.lib();

        bool callResult = false;
        assembly {
            calldatacopy(0x0, 0x0, calldatasize)
            callResult := delegatecall(sub(gas, 10000), target, 0x0, calldatasize, 0, len)
        }

        require (callResult);
        
        assembly {
            return(0, len)
        }
    }
```

The only issue I see is that we can't tell what the inner exception was: assert-style or require-style. But so far I'm OK with this.

**Comment by maraoz** [comment]
Awesome! Thanks :)
